### ISSUE TITLE
Exception on non-existent file

### ISSUE THREAD

**Issue by JhonnyJason** [JhonnyJason/gitmodules-handler#1]
In the case when the file does not exist, sometimes the call of "fs.close(path)" will throw an exception.

This needs do be investigated furtherly why that happens.

In any case the thrown exception is a nuissance, it might be ignored in most cases, as the file has been created then. A next call will fill it with the appropriate content.

**Comment by JhonnyJason** [comment]
Error!
TypeError: fs.close is not a function
TypeError: fs.close is not a function
    at Object.readNewGitmodulesFile (/home/lenny/thingies/thingysync/output/node_modules/gitmodules-file-handler/index.js:178:31)
    at async handleLevel (/home/lenny/thingies/thingysync/output/pullcommandmodule.js:100:21)
    at async Promise.all (index 1)
    at async handleLevel (/home/lenny/thingies/thingysync/output/pullcommandmodule.js:111:5)
    at async Object.pullcommandmodule.execute (/home/lenny/thingies/thingysync/output/pullcommandmodule.js:125:7)
    at async Object.mainprocessmodule.execute (/home/lenny/thingies/thingysync/output/mainprocessmodule.js:57:9)
    at async Object.startupmodule.cliStartup (/home/lenny/thingies/thingysync/output/startupmodule.js:65:7)
